# Numpy-Statistical Function

- 1-amin() and amax()-return the minimum and the maximum from the elements in the given array along the specified axis.
- 2-numpy.ptp()-function returns the range (maximum-minimum) of values along an axis.
- 3-numpy.median()-Median is defined as the value separating the higher half of a data sample from the lower half.
- 4-numpy.mean()-returns the arithmetic mean of elements in the array.
- 5-numpy.average()-computes the weighted average of elements in an array according to their respective weight given in another   array.
- 6-Standard Deviation- the square root of the average of squared deviations from mean.
- 7-Variance-average of squared deviations, i.e., mean(abs(x - x.mean())**2).

In [3]:
#1-amin() and amax()-return the minimum and the maximum from the elements in the given array along the specified axis.
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])

In [4]:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [5]:
#'Applying amin() function:for row' 
np.amin(a,1)

array([3, 3, 2])

In [7]:
#'Applying amin() function again:for column' 
np.amin(a,0) 

array([2, 4, 3])

In [8]:
#'Applying amax() function:' 
np.amax(a)

9

In [9]:
#'Applying amax() function again:' 
np.amax(a, axis = 0)

array([8, 7, 9])

In [10]:
#2-numpy.ptp()-function returns the range (maximum-minimum) of values along an axis.
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

In [11]:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [12]:
#'Applying ptp() function:(9-2)=7' 
np.ptp(a)

7

In [13]:
#'Applying ptp() function along axis 1:on row' 
np.ptp(a, axis = 1) 

array([4, 5, 7])

In [14]:
#'Applying ptp() function along axis 0:on column'
np.ptp(a, axis = 0) 

array([6, 3, 6])

In [17]:
#3-numpy.median()-Median is defined as the value separating the higher half of a data sample from the lower half.
a = np.array([[30,65,70],[80,95,10],[50,90,60]])

In [18]:
a

array([[30, 65, 70],
       [80, 95, 10],
       [50, 90, 60]])

In [19]:
#'Applying median() function:' 
np.median(a)

65.0

In [20]:
#'Applying median() function along axis 0:' 
np.median(a, axis = 0)

array([50., 90., 60.])

In [21]:
#'Applying median() function along axis 1:' 
np.median(a, axis = 1)

array([65., 80., 60.])

In [22]:
#4-numpy.mean()-returns the arithmetic mean of elements in the array.
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

In [23]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [24]:
#'Applying mean() function:' 
np.mean(a) 

3.6666666666666665

In [25]:
#'Applying mean() function along axis 0:' 
np.mean(a, axis = 0) 

array([2.66666667, 3.66666667, 4.66666667])

In [26]:
#Applying mean() function along axis 1:' 
np.mean(a, axis = 1)

array([2., 4., 5.])

In [27]:
#5-numpy.average()-computes the weighted average of elements in an array according to their respective weight given in another array.
a = np.array([1,2,3,4]) 

In [28]:
a

array([1, 2, 3, 4])

In [29]:
#'Applying average() function:' 
np.average(a)

2.5

In [30]:
# this is same as mean when weight is not specified 
wts = np.array([4,3,2,1]) 

In [31]:
wts

array([4, 3, 2, 1])

In [32]:
#'Applying average() function again:' 
np.average(a,weights = wts) 

2.0

In [33]:
#6-Standard Deviation- the square root of the average of squared deviations from mean.
#std = sqrt(mean(abs(x - x.mean())**2))
np.std([1,2,3,4])

1.118033988749895

In [34]:
#7-Variance-average of squared deviations, i.e., mean(abs(x - x.mean())**2).
np.var([1,2,3,4])

1.25