# Numpy-Array Manipulation 

- This includes
- 1-Changing Shape
- 2-Transpose Operations
- 3-Changing Dimensions
- 4-Joining Array
- 5-Splitting Array
- 6-Adding/Removing Array

# Changing Shape

- 1-reshape-Gives a new shape to an array without changing its data
- 2-flat-A 1-D iterator over the array
- 3-flatten-Returns a copy of the array collapsed into one dimension

In [1]:
#1-reshape-Gives a new shape to an array without changing its data
#numpy.reshape(arr, newshape, order)
import numpy as np
a = np.arange(8)


In [2]:
#print The original array
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
b = a.reshape(4,2)

In [4]:
#print rehsaped array
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [5]:
#2-flat-A 1-D iterator over the array
#After applying the flat function
# returns element corresponding to index in flattened array 
a.flat[5]

5

In [6]:
a.flat[0]

0

In [7]:
a.flat[1]

1

In [8]:
#3-flatten-Returns a copy of the array collapsed into one dimension
#ndarray.flatten(order)
a = np.arange(8).reshape(2,4) 

In [9]:
#The original array is
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
#The flattened array is
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
#The flattened array in F-style ordering
#order=f: column major
a.flatten(order = 'F')

array([0, 4, 1, 5, 2, 6, 3, 7])

In [12]:
#order=A:flatten in column-major order
a.flatten(order = 'A')

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
#order=K: flatten a in the order the elements occur in the memory
a.flatten(order = 'k')

array([0, 1, 2, 3, 4, 5, 6, 7])

# Transpose Operations

- 1-transpose-Changes the dimensions of an array
- 2-ndarray.T-Same as self.transpose()
- 3-swapaxes-Interchanges the two axes of an array

In [14]:
#1-transpose-Changes the dimensions of an array
#numpy.transpose(arr, axes)
a = np.arange(12).reshape(3,4) 

In [15]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
#The transposed array is
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [17]:
#2-ndarray.T-Same as self.transpose()
#behaves similar to numpy.transpose
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [18]:
#3-swapaxes-Interchanges the two axes of an array
#numpy.swapaxes(arr, axis1, axis2)
#It creates a 3 dimensional ndarray
a = np.arange(8).reshape(2,2,2) 

In [19]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
# now swap numbers between axis 0 (along depth) and axis 2 (along width) 
np.swapaxes(a, 2, 0)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

# Changing Dimensions

- 1-broadcast_to-broadcast an array to new shape
- 2-expand_dim-expand the shape of an array
- 3-squeeze-Removes single-dimensional entries from the shape of an array

In [21]:
#1-broadcast_to-broadcast an array to new shape
# returns a read-only view on the original array.
#numpy.broadcast_to(array, shape, subok)
a = np.arange(4).reshape(1,4)

In [22]:
#original array
a

array([[0, 1, 2, 3]])

In [23]:
#After applying the broadcast_to function
np.broadcast_to(a,(4,4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [24]:
#2-expand_dim-expand the shape of an array by inserting a new axis at the specified position.
#numpy.expand_dims(arr, axis)
x = np.array(([1,2],[3,4])) 

In [25]:
x

array([[1, 2],
       [3, 4]])

In [28]:
# insert axis at position 0
a=np.expand_dims(x, axis = 0) 

In [29]:
a

array([[[1, 2],
        [3, 4]]])

In [30]:
a.shape

(1, 2, 2)

In [31]:
# insert axis at position 1 
b=np.expand_dims(x, axis = 1)

In [32]:
b

array([[[1, 2]],

       [[3, 4]]])

In [33]:
b.shape

(2, 1, 2)

In [34]:
#3-squeeze-Removes single-dimensional entries from the shape of an array
#numpy.squeeze(arr, axis)
x = np.arange(9).reshape(1,3,3) 

In [35]:
x

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [36]:
x.shape

(1, 3, 3)

In [37]:
y = np.squeeze(x)

In [38]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
y.shape

(3, 3)

# Array Joins

- 1-concatenate-Joins a sequence of arrays along an existing axis
- 2-stack-Joins a sequence of arrays along a new axis
- 3-hstack-Stacks arrays in sequence horizontally (column wise)
- 4-vstack-Stacks arrays in sequence vertically (row wise)

In [40]:
#1-concatenate-Joins a sequence of arrays along an existing axis
#numpy.concatenate((a1, a2, ...), axis)
a = np.array([[1,2],[3,4]])

In [41]:
#First array
a

array([[1, 2],
       [3, 4]])

In [42]:
#Second array
b = np.array([[5,6],[7,8]])

In [43]:
b

array([[5, 6],
       [7, 8]])

In [44]:
# both the arrays are of same dimensions 
#Joining the two arrays along axis 0
np.concatenate((a,b)) 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [45]:
#joining the two arrays along axis 1
np.concatenate((a,b),axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [46]:
#2-stack-Joins a sequence of arrays along a new axis
#numpy.stack(arrays, axis)
#First Array
a = np.array([[1,2],[3,4]]) 

In [47]:
a

array([[1, 2],
       [3, 4]])

In [48]:
#Second Array
b = np.array([[5,6],[7,8]]) 

In [49]:
b

array([[5, 6],
       [7, 8]])

In [50]:
#Stack the two arrays along axis 0
np.stack((a,b),0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
#Stack the two arrays along axis 1
np.stack((a,b),1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [58]:
#3-hstack-Stacks arrays in sequence horizontally (column wise)
a = np.array([[1,2],[3,4]]) 

In [59]:
a

array([[1, 2],
       [3, 4]])

In [60]:
b = np.array([[5,6],[7,8]]) 

In [61]:
b

array([[5, 6],
       [7, 8]])

In [62]:
#Horizontal stacking:
c = np.hstack((a,b)) 

In [63]:
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [64]:
#vstack-Stacks arrays in sequence vertically (row wise)
d= np.vstack((a,b)) 

In [65]:
d

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Splitting Arrays

- 1-split-Splits an array into multiple sub-arrays
- 2-hsplit-Splits an array into multiple sub-arrays horizontally (column-wise)
- 3-vsplit-splits an array into multiple sub-arrays vertically (row-wise)

In [66]:
#1-split-Splits an array into multiple sub-arrays
#numpy.split(ary, indices_or_sections, axis)
a = np.arange(9) 

In [67]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
#Split the array in 3 equal-sized subarrays
b = np.split(a,3) 

In [69]:
b

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [70]:
#Split the array at positions indicated in 1-D array:
b = np.split(a,[4,7])

In [71]:
b

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [72]:
b = np.split(a,[2,5])

In [73]:
b

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8])]

In [74]:
#2-hsplit-Splits an array into multiple sub-arrays horizontally (column-wise)
a = np.arange(16).reshape(4,4)

In [75]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
#'Horizontal splitting:' 
b = np.hsplit(a,2)

In [77]:
b

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [79]:
b = np.hsplit(a,4)

In [80]:
b

[array([[ 0],
        [ 4],
        [ 8],
        [12]]), array([[ 1],
        [ 5],
        [ 9],
        [13]]), array([[ 2],
        [ 6],
        [10],
        [14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

In [83]:
#3-vsplit-splits an array into multiple sub-arrays vertically (row-wise)
#where axis is 1 indicating a vertical split regardless of the dimension of the input array.
a = np.arange(16).reshape(4,4) 

In [84]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
#'Vertical splitting:' 
b = np.vsplit(a,2)

In [86]:
b

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [88]:
#'Vertical splitting:' 
b = np.vsplit(a,4)

In [89]:
b

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

# Adding/Removing Elements

- 1-resize-Returns a new array with the specified shape
- 2-insert-Inserts the values along the given axis before the given indices
- 3-delete-Returns a new array with sub-arrays along an axis deleted
- 4-unique-Finds the unique elements of an array

In [90]:
#1-resize-Returns a new array with the specified shape
#If the new size is greater than the original, the repeated copies of entries in the original are contained.
#numpy.resize(arr, shape)
a = np.array([[1,2,3],[4,5,6]]) 

In [91]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
#'The shape of first array:' 
a.shape 

(2, 3)

In [93]:
b = np.resize(a, (3,2))

In [94]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]:
#'The shape of second array:' 
b.shape

(3, 2)

In [96]:
# Observe that first row of a is repeated in b since size is bigger
#Resize the second array:' 
b = np.resize(a,(3,3)) 

In [97]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [98]:
#2-insert-Inserts the values along the given axis before the given indices
#numpy.insert(arr, obj, values, axis)
a = np.array([[1,2],[3,4],[5,6]]) 

In [99]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
#'Axis parameter not passed. The input array is flattened before insertion.'
np.insert(a,3,[11,12])

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [107]:
#'Axis parameter passed. The values array is broadcast to match input array.'
#'Broadcast along axis 0:' 
np.insert(a,1,[11],axis = 0) 

array([[ 1,  2],
       [11, 11],
       [ 3,  4],
       [ 5,  6]])

In [102]:
#Broadcast along axis 1:' 
np.insert(a,1,11,axis = 1)

array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

In [108]:
np.insert(a,0,11,axis = 1)

array([[11,  1,  2],
       [11,  3,  4],
       [11,  5,  6]])

In [2]:
#3-delete-Returns a new array with sub-arrays along an axis deleted
#Numpy.delete(arr, obj, axis)
import numpy as np
a = np.arange(12).reshape(3,4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
#'Array flattened before delete operation as axis not used:' 
np.delete(a,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [5]:
#'Column 2 deleted:'  
np.delete(a,1,axis = 1)

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

In [6]:
#'Column 1 deleted:'  
np.delete(a,0,axis = 1)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [11]:
#4-unique-Finds the unique elements of an array
#numpy.unique(arr, return_index, return_inverse, return_counts)
a = np.array([5,2,6,2,7,5,6,8,2,9]) 


In [12]:
a

array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])

In [13]:
#'Unique values of first array:' 
u = np.unique(a)

In [14]:
u

array([2, 5, 6, 7, 8, 9])

In [15]:
#'Unique array and Indices array:' 
u,indices = np.unique(a, return_index = True) 

In [16]:
u,indices

(array([2, 5, 6, 7, 8, 9]), array([1, 0, 2, 4, 7, 9], dtype=int64))