# Numpy-Sort, Search and Counting Function

- 1-numpy.sort()-returns a sorted copy of the input array.
- 2-numpy.argsort()-performs an indirect sort on input array, along the given axis 
- 3-numpy.lexsort()-function performs an indirect sort using a sequence of keys.
- 4-numpy.nonzero()-returns the indices of non-zero elements in the input array.
- 5-numpy.where()-returns the indices of elements in an input array where the given condition is satisfied.
- 6-numpy.extract()-function returns the elements satisfying any condition.
- 7-numpy.argmax() and numpy.argmin()-return the indices of maximum and minimum elements respectively along the given axis.

In [1]:
#1-numpy.sort()-returns a sorted copy of the input array.
#numpy.sort(a, axis, kind, order)
import numpy as np  
a = np.array([[3,7],[9,1]])

In [2]:
a

array([[3, 7],
       [9, 1]])

In [3]:
#'Applying sort() function:' 
np.sort(a) 

array([[3, 7],
       [1, 9]])

In [4]:
#'Sort along axis 0:' 
np.sort(a, axis = 0) 

array([[3, 1],
       [9, 7]])

In [5]:
#'Sort along axis 1:' 
np.sort(a, axis = 1) 

array([[3, 7],
       [1, 9]])

In [6]:
# Order parameter in sort function 
dt = np.dtype([('name', 'S10'),('age', int)]) 
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt) 

In [7]:
dt

dtype([('name', 'S10'), ('age', '<i4')])

In [8]:
a

array([(b'raju', 21), (b'anil', 25), (b'ravi', 17), (b'amar', 27)],
      dtype=[('name', 'S10'), ('age', '<i4')])

In [9]:
#'Order by name:' 
np.sort(a, order = 'name')

array([(b'amar', 27), (b'anil', 25), (b'raju', 21), (b'ravi', 17)],
      dtype=[('name', 'S10'), ('age', '<i4')])

In [10]:
#2-numpy.argsort()-performs an indirect sort on input array, along the given axis
x = np.array([3, 1, 2]) 

In [11]:
x

array([3, 1, 2])

In [12]:
#'Applying argsort() to x:' 
y = np.argsort(x) 

In [13]:
y

array([1, 2, 0], dtype=int64)

In [14]:
#'Reconstruct original array in sorted order:' 
x[y] 

array([1, 2, 3])

In [15]:
#3-numpy.lexsort()-function performs an indirect sort using a sequence of keys.
nm = ('raju','anil','ravi','amar') 
dv = ('f.y.', 's.y.', 's.y.', 'f.y.') 

In [16]:
nm

('raju', 'anil', 'ravi', 'amar')

In [17]:
dv

('f.y.', 's.y.', 's.y.', 'f.y.')

In [18]:
ind = np.lexsort((dv,nm))

In [19]:
ind

array([3, 1, 0, 2], dtype=int64)

In [20]:
#4-numpy.nonzero()-returns the indices of non-zero elements in the input array.
a = np.array([[30,40,0],[0,20,10],[50,0,60]]) 

In [21]:
a

array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

In [22]:
#'Applying nonzero() function:' 
np.nonzero (a)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 1, 2, 0, 2], dtype=int64))

In [24]:
b = np.array([30,40,0,0,20,10,50,0,60])

In [25]:
b

array([30, 40,  0,  0, 20, 10, 50,  0, 60])

In [26]:
np.nonzero (b)

(array([0, 1, 4, 5, 6, 8], dtype=int64),)

In [34]:
#5-numpy.where()-returns the indices of elements in an input array where the given condition is satisfied.
x = np.arange(9).reshape(3, 3) 


In [35]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
#Indices of elements > 3' 
y = np.where(x > 3) 

In [37]:
y

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [31]:
b = np.array([30,40,0,0,20,10,50,0,60])

In [32]:
z=np.where(b>30)

In [33]:
z

(array([1, 6, 8], dtype=int64),)

In [38]:
#Use these indices to get elements satisfying the condition' 
x[y]

array([4, 5, 6, 7, 8])

In [41]:
#6-numpy.extract()-function returns the elements satisfying any condition.
x = np.arange(9).reshape(3, 3) 

In [42]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
# define a condition 
condition = np.mod(x,2) == 0 

In [44]:
#'Element-wise value of condition' 
condition 

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [45]:
#'Extract elements using condition' 
np.extract(condition, x)

array([0, 2, 4, 6, 8])

In [46]:
#7-numpy.argmax() and numpy.argmin()-return the indices of maximum and minimum elements respectively along the given axis.
a = np.array([[30,40,70],[80,20,10],[50,90,60]])

In [47]:
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [48]:
#'Our array is:' 
a 

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [49]:
#'Applying argmax() function:' 
np.argmax(a)

7

In [50]:
#'Array containing indices of maximum along axis 0:' 
maxindex = np.argmax(a, axis = 0)

In [51]:
maxindex

array([1, 2, 0], dtype=int64)

In [52]:
#'Array containing indices of maximum along axis 1:' 
maxindex = np.argmax(a, axis = 1) 

In [53]:
maxindex

array([2, 0, 1], dtype=int64)

In [54]:
#'Applying argmin() function:' 
minindex = np.argmin(a) 

In [55]:
minindex

5

In [60]:
#'Flattened array:' 
a.flatten()[minindex]

array([30, 70, 30])

In [56]:
#'Flattened array along axis 0:' 
minindex = np.argmin(a, axis = 0) 

In [57]:
minindex

array([0, 1, 1], dtype=int64)

In [58]:
#'Flattened array along axis 1:' 
minindex = np.argmin(a, axis = 1)

In [59]:
minindex

array([0, 2, 0], dtype=int64)